name: smart_reader
description: "DocuScan - Card & Passbook OCR Scanner App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.13.0
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "web/icons/banking-system-extracted.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "web/icons/banking-system-extracted.png"
